import { Suspense } from "react";
import type { Metadata } from "next";
import "./global.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import { ReduxProviderFront } from "../../store/ReduxProviderFront";
import { CountryProvider } from "../../context/CountryContext";
import { SearchProvider } from "../../context/SearchContext";
import { Poppins } from "next/font/google";
import MainTemplate from "@/components/frontendcomponents/template/MainTemplate";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <ReduxProviderFront>
        <SearchProvider>
          <CountryProvider>
            <body cz-shortcut-listen="true">
              <NextTopLoader showSpinner={false} />
              <Suspense fallback={<div>Loading...</div>}>
                <MainTemplate>
                  {children}
                </MainTemplate>
              </Suspense>
              <Toaster
                position="top-center"
                reverseOrder={true}
                toastOptions={{
                  duration: 5000,
                  style: {
                    borderRadius: "8px",
                    padding: "12px 16px",
                    color: "#fff",
                  },
                  success: {
                    style: { background: "#22c55e" },
                    iconTheme: {
                      primary: "#ffffff",
                      secondary: "#16a34a",
                    },
                  },
                  error: {
                    style: { background: "#ef4444" },
                    iconTheme: {
                      primary: "#ffffff",
                      secondary: "#b91c1c",
                    },
                  },
                }}
              />
            </body>
          </CountryProvider>
        </SearchProvider>
      </ReduxProviderFront>
    </html>
  );
}
